### ISSUE TITLE
can you please make this work for colab free

### ISSUE THREAD

**Issue by loboere** [xuduo35/UniTune#1]
it would be great if you can make it work in free colab

**Comment by xuduo35** [comment]
Good suggestion, I'll try later.

**Comment by xuduo35** [comment]
@loboere https://colab.research.google.com/drive/1V6nM-iGHQi7TDqMDEn4ohO6-MmiQMm6L?usp=sharing

**Comment by loboere** [comment]
thanks for the colab, I see that the colab is missing some parameters like t0 will add it soon?

**Comment by xuduo35** [comment]
Try this: https://colab.research.google.com/drive/1WA1CDQrKDbaLjvfxvQXyUGsZ5ldx9IIe?usp=sharing
